// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { createSupabaseClientOrFallback } from '@/lib/supabaseFallback';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const { client: supabase } = createSupabaseClientOrFallback(
  SUPABASE_URL,
  SUPABASE_KEY,
  (url, key) =>
    createClient<Database>(url, key, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    }),
  { context: "integration" },
);

export { supabase };
